# -*- coding: utf-8 -*-
"""SPCC_EXP03.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pw1jrpNx3OS9EB7Xiug3dNstqrjf4ci2
"""

import re

keyword = ['break','case','char','const','countinue','deafult','do','int','else','enum','extern','float','for','goto','if','long','register','return','short','signed','sizeof','static','switch','typedef','union','unsigned','void','volatile','while']
built_in_functions = ['clrscr()','getch()','main()']
operators = ['+','-','*','/','%','==','!=','>','<','>=','<=','&&','||','!','&','|','^','~','>>','<<','=','+=','-=','*=']
specialsymbol = ['@','#','$','_','!']
separator = [',',':',';','\n','\t','{','}','(',')','[',']']


input = open('lexical.txt','r+')
contents = input.read()
output = open('analysed.txt','w')
splitCode = contents.split() #split program in word based on space
length = len(splitCode)      # count the number of word in program
lexical=""
for i in range(0,length):
    if splitCode[i] in keyword:
        lexical=("Keyword --> "+ splitCode[i])
    elif splitCode[i] in operators:
        lexical=("Operators --> "+ splitCode[i])
    elif splitCode[i] in specialsymbol:
        lexical=("Special Operator --> "+ splitCode[i])
    elif splitCode[i] in built_in_functions:
        lexical=("Built_in Function --> "+ splitCode[i])
    elif splitCode[i] in separator:
        lexical=("Separator --> "+ splitCode[i])
    elif re.match(r'(#include*).*', splitCode[i]):
        lexical=("Header File --> "+ splitCode[i])
    elif re.match(r'(printf*).*', splitCode[i]):
        lexical=("Built_in Function --> printf")
    elif re.match(r'(scanf*).*', splitCode[i]):
        lexical=("Built_in_Function --> scanf")
    elif re.match(r'^[-+]?[0-9]+$', splitCode[i]):
        lexical=("Numerals --> "+ splitCode[i])
    elif re.match(r"^[^\d\W]\w*\Z", splitCode[i]):
        lexical=("Identifier --> "+ splitCode[i])
    print(lexical)
    output.write(lexical+"\n")
input.close()
output.close()